runtime: nodejs20
service: frontend

handlers:
  - url: /static
    static_dir: build/static

  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json

  - url: /images/(.*)
    static_files: build/images/\1
    upload: build/images/(.*)

  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  REACT_APP_API_BASE_URL: "https://personal-web-page-tenmou-vi.uc.r.appspot.com"
